<?xml version="1.0" encoding="UTF-8"?>
<definitions name="PIP3A20ResponderRACResult"
    targetNamespace="http://lspi.wiai.uniba.de/ebBP-prototype/wsdl/composablePIP3A20Responder/PIP3A20ResponderRACResult"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:tns="http://lspi.wiai.uniba.de/ebBP-prototype/wsdl/composablePIP3A20Responder/PIP3A20ResponderRACResult"
    xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:corr="http://lspi.wiai.uniba.de/ebBP-prototype/wsdl/correlation-1-0"
    xmlns:mb="http://lspi.wiai.uniba.de/ebBP-prototype/xsd/header-1-0"
    xmlns:ns="http://lspi.wiai.uniba.de/ebBP-prototype/xsd/controlMsg-1-0"
    xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop">

    <plnk:partnerLinkType name="PIP3A20ResponderRACResult">
        <plnk:role name="PIP3A20ResponderRACResultPortTypeRole" portType="tns:PIP3A20ResponderRACResultPortType"/>
    </plnk:partnerLinkType>

    <vprop:propertyAlias propertyName="corr:prop_CollaborationIdentifier" messageType="tns:DropReceiptAcknowledgementMsg" part="DropReceiptAcknowledgementPart">
        <vprop:query>mb:TransactionMetaBlock/mb:InstanceIdentifier</vprop:query>
    </vprop:propertyAlias>
    <vprop:propertyAlias propertyName="corr:prop_CollaborationIdentifier" messageType="tns:DropExceptionMsg" part="DropExceptionPart">
        <vprop:query>mb:TransactionMetaBlock/mb:InstanceIdentifier</vprop:query>
    </vprop:propertyAlias>

    <import location="Correlation-composable.wsdl" namespace="http://lspi.wiai.uniba.de/ebBP-prototype/wsdl/correlation-1-0"/>
    <types>
        <xsd:schema targetNamespace="http://lspi.wiai.uniba.de/ebBP-prototype/wsdl/composablePIP3A20Responder/PIP3A20ResponderRACResult">
            <xsd:import namespace="http://lspi.wiai.uniba.de/ebBP-prototype/xsd/controlMsg-1-0" schemaLocation="xsd/control/controlMessaging.xsd"/>
        </xsd:schema>
    </types>
    <!--
        DropReceiptAck
    -->
    <message name="DropReceiptAcknowledgementMsg">
        <part name="DropReceiptAcknowledgementPart" element="ns:WrappedReceiptAcknowledgementMessage"/>
    </message>
    <!--
        Needed for dropping ReceiptExceptionMessage
    -->
    <message name="DropExceptionMsg">
        <part name="DropExceptionPart" element="ns:WrappedExceptionMessage"/>
    </message>
    <portType name="PIP3A20ResponderRACResultPortType">
        <operation name="DropReceiptAcknowledgementOp">
            <input name="input1" message="tns:DropReceiptAcknowledgementMsg"/>
        </operation>
        <operation name="DropExceptionOp">
            <input name="input2" message="tns:DropExceptionMsg"/>
        </operation>
    </portType>
    <binding name="PIP3A20ResponderRACResultBinding" type="tns:PIP3A20ResponderRACResultPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="DropReceiptAcknowledgementOp">
            <soap:operation/>
            <input name="input1">
                <soap:body use="literal"/>
            </input>
        </operation>
        <operation name="DropExceptionOp">
            <soap:operation/>
            <input name="input2">
                <soap:body use="literal"/>
            </input>
        </operation>
    </binding>
    <service name="PIP3A20ResponderRACResultService">
        <port name="PIP3A20ResponderRACResultPort" binding="tns:PIP3A20ResponderRACResultBinding">
            <soap:address location="http://localhost:9081/PIP3A20ResponderRACResultService/PIP3A20ResponderRACResultPort"/>
        </port>
    </service>

</definitions>





