<?xml version="1.0" encoding="UTF-8"?>
<definitions name="PIP3A20ResponderMasterCallback"
    targetNamespace="http://lspi.wiai.uniba.de/ebBP-prototype/wsdl/composablePIP3A20Responder/PIP3A20ResponderMasterCallback"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:tns="http://lspi.wiai.uniba.de/ebBP-prototype/wsdl/composablePIP3A20Responder/PIP3A20ResponderMasterCallback"
    xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:ns0="http://lspi.wiai.uniba.de/ebBP-prototype/xsd/Wrapped-DTDBased-PurchaseOrderConfirmationNotification-1-0"
    xmlns:mb="http://lspi.wiai.uniba.de/ebBP-prototype/xsd/header-1-0"
    xmlns:corr="http://lspi.wiai.uniba.de/ebBP-prototype/wsdl/correlation-1-0">

    <plnk:partnerLinkType name="PIP3A20ResponderMasterCallback">
        <plnk:role name="PIP3A20ResponderMasterCallbackPortTypeRole" portType="tns:PIP3A20ResponderMasterCallbackPortType"/>
    </plnk:partnerLinkType>

    <types>
        <xsd:schema targetNamespace="http://lspi.wiai.uniba.de/ebBP-prototype/wsdl/composablePIP3A20Responder/PIP3A20ResponderMasterCallback">
            <xsd:import namespace="http://lspi.wiai.uniba.de/ebBP-prototype/xsd/Wrapped-DTDBased-PurchaseOrderConfirmationNotification-1-0" schemaLocation="xsd/3A20/Wrapped_3A20_MS_V01_00_PurchaseOrderConfirmationNotification.xsd"/>
        </xsd:schema>
    </types>
    <message name="txResultMsg">
        <part name="txResultPart" element="ns0:txResultMessage"/>
    </message>
    <portType name="PIP3A20ResponderMasterCallbackPortType">
        <operation name="txResultOp">
            <input name="input1" message="tns:txResultMsg"/>
        </operation>
    </portType>
    <binding name="PIP3A20ResponderMasterCallbackBinding" type="tns:PIP3A20ResponderMasterCallbackPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="txResultOp">
            <soap:operation/>
            <input name="input1">
                <soap:body use="literal"/>
            </input>
        </operation>
    </binding>
    <service name="PIP3A20ResponderMasterCallbackService">
        <port name="PIP3A20ResponderMasterCallbackPort" binding="tns:PIP3A20ResponderMasterCallbackBinding">
            <soap:address location="http://localhost:8080/PIP3A20ResponderMasterCallbackService/PIP3A20ResponderMasterCallbackPort"/>
        </port>
    </service>


</definitions>


