package bpellint;

import java.util.Arrays;
import java.util.List;

public class SAViolationTestData {
    public static List<Object[]> saViolationTests() {
        Object[][] data = new Object[][]{

                {"Testcases/rules/SA00001/Notification.bpel", "1"},
                {"Testcases/rules/SA00001/SolicitResponse.bpel", "1"},

                {"Testcases/rules/SA00002/OverloadedOperationNames.bpel", "2"},

                {"Testcases/rules/SA00003/ExitOnStandardFaultButCatchingStandardFaultInDirectFaultHandlers_IGNORE_ME.bpel", "3"},
                {"Testcases/rules/SA00003/ExitOnStandardFaultButCatchingStandardFaultInDirectFaultHandlersInProcess_IGNORE_ME.bpel", "3"},
                {"Testcases/rules/SA00003/ExitOnStandardFaultButCatchingStandardFaultInIndirectFaultHandlers_IGNORE_ME.bpel", "3"},
                {"Testcases/rules/SA00003/ExitOnStandardFaultButCatchingStandardFaultInIndirectNestedFaultHandlers_IGNORE_ME.bpel", "3"},
                {"Testcases/rules/SA00003/ExitOnStandardFaultButCatchingStandardFaultInNestedFaultHandlers_IGNORE_ME.bpel", "3"},
                {"Testcases/rules/SA00003/ProcessExitAndCatchAR.bpel", "3"},
                {"Testcases/rules/SA00003/ProcessExitAndCatchCCF.bpel", "3"},
                {"Testcases/rules/SA00003/ProcessExitAndCatchCRec.bpel", "3"},
                {"Testcases/rules/SA00003/ProcessExitAndCatchCReq.bpel", "3"},
                {"Testcases/rules/SA00003/ProcessExitAndCatchCV.bpel", "3"},
                {"Testcases/rules/SA00003/ProcessExitAndCatchIBC.bpel", "3"},
                {"Testcases/rules/SA00003/ProcessExitAndCatchIEV.bpel", "3"},
                {"Testcases/rules/SA00003/ProcessExitAndCatchIV.bpel", "3"},
                {"Testcases/rules/SA00003/ProcessExitAndCatchMAF.bpel", "3"},
                {"Testcases/rules/SA00003/ProcessExitAndCatchMRep.bpel", "3"},
                {"Testcases/rules/SA00003/ProcessExitAndCatchMReq.bpel", "3"},
                {"Testcases/rules/SA00003/ProcessExitAndCatchSIF.bpel", "3"},
                {"Testcases/rules/SA00003/ProcessExitAndCatchSF.bpel", "3"},
                {"Testcases/rules/SA00003/ProcessExitAndCatchSLEF.bpel", "3"},
                {"Testcases/rules/SA00003/ProcessExitAndCatchUPR.bpel", "3"},
                {"Testcases/rules/SA00003/ProcessExitAndCatchUV.bpel", "3"},
                {"Testcases/rules/SA00003/ProcessExitAndCatchUR.bpel", "3"},
                {"Testcases/rules/SA00003/ProcessExitAndCatchXIS.bpel", "3"},
                {"Testcases/rules/SA00003/ProcessExitAndCatchXSNF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeInhertedProcessYesCatchAR.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeInhertedProcessYesCatchCCF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeInhertedProcessYesCatchCRec.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeInhertedProcessYesCatchCReq.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeInhertedProcessYesCatchCV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeInhertedProcessYesCatchIBC.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeInhertedProcessYesCatchIEV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeInhertedProcessYesCatchIV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeInhertedProcessYesCatchMAF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeInhertedProcessYesCatchMRep.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeInhertedProcessYesCatchMReq.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeInhertedProcessYesCatchSIF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeInhertedProcessYesCatchSF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeInhertedProcessYesCatchSLEF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeInhertedProcessYesCatchUPR.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeInhertedProcessYesCatchUV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeInhertedProcessYesCatchUR.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeInhertedProcessYesCatchXIS.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeInhertedProcessYesCatchXSNF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeYesProcessDefaultCatchAR.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeYesProcessDefaultCatchCCF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeYesProcessDefaultCatchCRec.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeYesProcessDefaultCatchCReq.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeYesProcessDefaultCatchCV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeYesProcessDefaultCatchIBC.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeYesProcessDefaultCatchIEV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeYesProcessDefaultCatchIV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeYesProcessDefaultCatchMAF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeYesProcessDefaultCatchMRep.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeYesProcessDefaultCatchMReq.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeYesProcessDefaultCatchSIF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeYesProcessDefaultCatchSF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeYesProcessDefaultCatchSLEF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeYesProcessDefaultCatchUPR.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeYesProcessDefaultCatchUV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeYesProcessDefaultCatchUR.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeYesProcessDefaultCatchXIS.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeYesProcessDefaultCatchXSNF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeYesProcessNoCatchAR.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeYesProcessNoCatchCCF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeYesProcessNoCatchCRec.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeYesProcessNoCatchCReq.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeYesProcessNoCatchCV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeYesProcessNoCatchIBC.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeYesProcessNoCatchIEV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeYesProcessNoCatchIV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeYesProcessNoCatchMAF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeYesProcessNoCatchMRep.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeYesProcessNoCatchMReq.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeYesProcessNoCatchSIF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeYesProcessNoCatchSF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeYesProcessNoCatchSLEF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeYesProcessNoCatchUPR.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeYesProcessNoCatchUV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeYesProcessNoCatchUR.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeYesProcessNoCatchXIS.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeYesProcessNoCatchXSNF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeYesProcessYesCatchAR.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeYesProcessYesCatchCCF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeYesProcessYesCatchCRec.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeYesProcessYesCatchCReq.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeYesProcessYesCatchCV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeYesProcessYesCatchIBC.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeYesProcessYesCatchIEV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeYesProcessYesCatchIV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeYesProcessYesCatchMAF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeYesProcessYesCatchMRep.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeYesProcessYesCatchMReq.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeYesProcessYesCatchSIF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeYesProcessYesCatchSF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeYesProcessYesCatchSLEF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeYesProcessYesCatchUPR.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeYesProcessYesCatchUV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeYesProcessYesCatchUR.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeYesProcessYesCatchXIS.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritedScopeYesProcessYesCatchXSNF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritProcessYesCatchAR.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritProcessYesCatchCCF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritProcessYesCatchCRec.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritProcessYesCatchCReq.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritProcessYesCatchCV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritProcessYesCatchIBC.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritProcessYesCatchIEV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritProcessYesCatchIV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritProcessYesCatchMAF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritProcessYesCatchMRep.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritProcessYesCatchMReq.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritProcessYesCatchSIF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritProcessYesCatchSF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritProcessYesCatchSLEF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritProcessYesCatchUPR.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritProcessYesCatchUV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritProcessYesCatchUR.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritProcessYesCatchXIS.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeInheritProcessYesCatchXSNF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesProcessDefaultCatchAR.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesProcessDefaultCatchCCF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesProcessDefaultCatchCRec.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesProcessDefaultCatchCReq.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesProcessDefaultCatchCV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesProcessDefaultCatchIBC.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesProcessDefaultCatchIEV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesProcessDefaultCatchIV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesProcessDefaultCatchMAF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesProcessDefaultCatchMRep.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesProcessDefaultCatchMReq.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesProcessDefaultCatchSIF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesProcessDefaultCatchSF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesProcessDefaultCatchSLEF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesProcessDefaultCatchUPR.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesProcessDefaultCatchUV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesProcessDefaultCatchUR.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesProcessDefaultCatchXIS.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesProcessDefaultCatchXSNF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesProcessNoCatchAR.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesProcessNoCatchCCF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesProcessNoCatchCRec.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesProcessNoCatchCReq.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesProcessNoCatchCV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesProcessNoCatchIBC.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesProcessNoCatchIEV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesProcessNoCatchIV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesProcessNoCatchMAF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesProcessNoCatchMRep.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesProcessNoCatchMReq.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesProcessNoCatchSIF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesProcessNoCatchSF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesProcessNoCatchSLEF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesProcessNoCatchUPR.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesProcessNoCatchUV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesProcessNoCatchUR.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesProcessNoCatchXIS.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesProcessNoCatchXSNF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesProcessYesCatchAR.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesProcessYesCatchCCF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesProcessYesCatchCRec.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesProcessYesCatchCReq.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesProcessYesCatchCV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesProcessYesCatchIBC.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesProcessYesCatchIEV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesProcessYesCatchIV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesProcessYesCatchMAF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesProcessYesCatchMRep.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesProcessYesCatchMReq.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesProcessYesCatchSIF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesProcessYesCatchSF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesProcessYesCatchSLEF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesProcessYesCatchUPR.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesProcessYesCatchUV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesProcessYesCatchUR.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesProcessYesCatchXIS.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesProcessYesCatchXSNF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeInhertedProcessDefaultCatchAR.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeInhertedProcessDefaultCatchCCF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeInhertedProcessDefaultCatchCRec.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeInhertedProcessDefaultCatchCReq.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeInhertedProcessDefaultCatchCV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeInhertedProcessDefaultCatchIBC.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeInhertedProcessDefaultCatchIEV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeInhertedProcessDefaultCatchIV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeInhertedProcessDefaultCatchMAF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeInhertedProcessDefaultCatchMRep.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeInhertedProcessDefaultCatchMReq.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeInhertedProcessDefaultCatchSIF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeInhertedProcessDefaultCatchSF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeInhertedProcessDefaultCatchSLEF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeInhertedProcessDefaultCatchUPR.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeInhertedProcessDefaultCatchUV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeInhertedProcessDefaultCatchUR.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeInhertedProcessDefaultCatchXIS.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeInhertedProcessDefaultCatchXSNF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeInhertedProcessNoCatchAR.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeInhertedProcessNoCatchCCF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeInhertedProcessNoCatchCRec.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeInhertedProcessNoCatchCReq.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeInhertedProcessNoCatchCV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeInhertedProcessNoCatchIBC.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeInhertedProcessNoCatchIEV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeInhertedProcessNoCatchIV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeInhertedProcessNoCatchMAF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeInhertedProcessNoCatchMRep.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeInhertedProcessNoCatchMReq.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeInhertedProcessNoCatchSIF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeInhertedProcessNoCatchSF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeInhertedProcessNoCatchSLEF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeInhertedProcessNoCatchUPR.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeInhertedProcessNoCatchUV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeInhertedProcessNoCatchUR.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeInhertedProcessNoCatchXIS.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeInhertedProcessNoCatchXSNF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeInhertedProcessYesCatchAR.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeInhertedProcessYesCatchCCF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeInhertedProcessYesCatchCRec.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeInhertedProcessYesCatchCReq.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeInhertedProcessYesCatchCV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeInhertedProcessYesCatchIBC.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeInhertedProcessYesCatchIEV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeInhertedProcessYesCatchIV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeInhertedProcessYesCatchMAF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeInhertedProcessYesCatchMRep.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeInhertedProcessYesCatchMReq.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeInhertedProcessYesCatchSIF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeInhertedProcessYesCatchSF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeInhertedProcessYesCatchSLEF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeInhertedProcessYesCatchUPR.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeInhertedProcessYesCatchUV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeInhertedProcessYesCatchUR.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeInhertedProcessYesCatchXIS.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeInhertedProcessYesCatchXSNF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeNoProcessDefaultCatchAR.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeNoProcessDefaultCatchCCF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeNoProcessDefaultCatchCRec.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeNoProcessDefaultCatchCReq.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeNoProcessDefaultCatchCV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeNoProcessDefaultCatchIBC.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeNoProcessDefaultCatchIEV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeNoProcessDefaultCatchIV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeNoProcessDefaultCatchMAF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeNoProcessDefaultCatchMRep.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeNoProcessDefaultCatchMReq.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeNoProcessDefaultCatchSIF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeNoProcessDefaultCatchSF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeNoProcessDefaultCatchSLEF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeNoProcessDefaultCatchUPR.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeNoProcessDefaultCatchUV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeNoProcessDefaultCatchUR.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeNoProcessDefaultCatchXIS.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeNoProcessDefaultCatchXSNF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeNoProcessNoCatchAR.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeNoProcessNoCatchCCF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeNoProcessNoCatchCRec.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeNoProcessNoCatchCReq.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeNoProcessNoCatchCV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeNoProcessNoCatchIBC.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeNoProcessNoCatchIEV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeNoProcessNoCatchIV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeNoProcessNoCatchMAF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeNoProcessNoCatchMRep.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeNoProcessNoCatchMReq.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeNoProcessNoCatchSIF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeNoProcessNoCatchSF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeNoProcessNoCatchSLEF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeNoProcessNoCatchUPR.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeNoProcessNoCatchUV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeNoProcessNoCatchUR.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeNoProcessNoCatchXIS.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeNoProcessNoCatchXSNF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeNoProcessYesCatchAR.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeNoProcessYesCatchCCF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeNoProcessYesCatchCRec.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeNoProcessYesCatchCReq.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeNoProcessYesCatchCV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeNoProcessYesCatchIBC.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeNoProcessYesCatchIEV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeNoProcessYesCatchIV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeNoProcessYesCatchMAF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeNoProcessYesCatchMRep.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeNoProcessYesCatchMReq.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeNoProcessYesCatchSIF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeNoProcessYesCatchSF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeNoProcessYesCatchSLEF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeNoProcessYesCatchUPR.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeNoProcessYesCatchUV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeNoProcessYesCatchUR.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeNoProcessYesCatchXIS.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeNoProcessYesCatchXSNF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeYesProcessDefaultCatchAR.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeYesProcessDefaultCatchCCF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeYesProcessDefaultCatchCRec.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeYesProcessDefaultCatchCReq.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeYesProcessDefaultCatchCV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeYesProcessDefaultCatchIBC.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeYesProcessDefaultCatchIEV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeYesProcessDefaultCatchIV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeYesProcessDefaultCatchMAF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeYesProcessDefaultCatchMRep.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeYesProcessDefaultCatchMReq.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeYesProcessDefaultCatchSIF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeYesProcessDefaultCatchSF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeYesProcessDefaultCatchSLEF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeYesProcessDefaultCatchUPR.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeYesProcessDefaultCatchUV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeYesProcessDefaultCatchUR.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeYesProcessDefaultCatchXIS.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeYesProcessDefaultCatchXSNF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeYesProcessNoCatchAR.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeYesProcessNoCatchCCF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeYesProcessNoCatchCRec.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeYesProcessNoCatchCReq.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeYesProcessNoCatchCV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeYesProcessNoCatchIBC.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeYesProcessNoCatchIEV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeYesProcessNoCatchIV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeYesProcessNoCatchMAF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeYesProcessNoCatchMRep.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeYesProcessNoCatchMReq.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeYesProcessNoCatchSIF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeYesProcessNoCatchSF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeYesProcessNoCatchSLEF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeYesProcessNoCatchUPR.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeYesProcessNoCatchUV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeYesProcessNoCatchUR.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeYesProcessNoCatchXIS.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeYesProcessNoCatchXSNF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeYesProcessYesCatchAR.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeYesProcessYesCatchCCF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeYesProcessYesCatchCRec.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeYesProcessYesCatchCReq.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeYesProcessYesCatchCV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeYesProcessYesCatchIBC.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeYesProcessYesCatchIEV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeYesProcessYesCatchIV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeYesProcessYesCatchMAF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeYesProcessYesCatchMRep.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeYesProcessYesCatchMReq.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeYesProcessYesCatchSIF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeYesProcessYesCatchSF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeYesProcessYesCatchSLEF.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeYesProcessYesCatchUPR.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeYesProcessYesCatchUV.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeYesProcessYesCatchUR.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeYesProcessYesCatchXIS.bpel", "3"},
                {"Testcases/rules/SA00003/ScopeYesScopeYesProcessYesCatchXSNF.bpel", "3"},

                {"Testcases/rules/SA00005/InvokeWithNonExistentPortType.bpel", "5"},
                {"Testcases/rules/SA00005/OnEventWithNonExistentPortType.bpel", "5"},
                {"Testcases/rules/SA00005/OnMessageWithNonExistentPortType.bpel", "5"},
                {"Testcases/rules/SA00005/ReceiveWithNonExistentPortType.bpel", "5"},
                {"Testcases/rules/SA00005/ReplyWithNonExistentPortType.bpel", "5"},

                {"Testcases/rules/SA00006/RethrowOutsideFaultHandlers.bpel", "6"},
                {"Testcases/rules/SA00006/RethrowInCompensationHandler.bpel", "6"},
                {"Testcases/rules/SA00006/RethrowInElse.bpel", "6"},
                {"Testcases/rules/SA00006/RethrowInElseIf.bpel", "6"},
                {"Testcases/rules/SA00006/RethrowInFlow.bpel", "6"},
                {"Testcases/rules/SA00006/RethrowInIf.bpel", "6"},
                {"Testcases/rules/SA00006/RethrowInOnAlarm.bpel", "6"},
                {"Testcases/rules/SA00006/RethrowInOnMessage.bpel", "6"},
                {"Testcases/rules/SA00006/RethrowInRepeatUntil.bpel", "6"},
                {"Testcases/rules/SA00006/RethrowInScope.bpel", "6"},
                {"Testcases/rules/SA00006/RethrowInTerminationHandlers.bpel", "6"},
                {"Testcases/rules/SA00006/RethrowInWhile.bpel", "6"},

                {"Testcases/rules/SA00007/CompensateScopeOutsideFaultHandlers.bpel", "7"},
                {"Testcases/rules/SA00007/CompensateScopeInElse.bpel", "7"},
                {"Testcases/rules/SA00007/CompensateScopeInElseIf.bpel", "7"},
                {"Testcases/rules/SA00007/CompensateScopeInFlow.bpel", "7"},
                {"Testcases/rules/SA00007/CompensateScopeInIf.bpel", "7"},
                {"Testcases/rules/SA00007/CompensateScopeInOnAlarm.bpel", "7"},
                {"Testcases/rules/SA00007/CompensateScopeInOnMessage.bpel", "7"},
                {"Testcases/rules/SA00007/CompensateScopeInRepeatUntil.bpel", "7"},
                {"Testcases/rules/SA00007/CompensateScopeInScope.bpel", "7,77"}, // <scope> can have a single activity. If <compensateSope> is this activity, no other <scope>/<invoke> can be placed in the same enclosing <scope>.
                {"Testcases/rules/SA00007/CompensateScopeInWhile.bpel", "7"},

                {"Testcases/rules/SA00008/CompensateOutsideFaultHandlers.bpel", "8"},
                {"Testcases/rules/SA00008/CompensateInElse.bpel", "8"},
                {"Testcases/rules/SA00008/CompensateInElseIf.bpel", "8"},
                {"Testcases/rules/SA00008/CompensateInFlow.bpel", "8"},
                {"Testcases/rules/SA00008/CompensateInIf.bpel", "8"},
                {"Testcases/rules/SA00008/CompensateInOnAlarm.bpel", "8"},
                {"Testcases/rules/SA00008/CompensateInOnMessage.bpel", "8"},
                {"Testcases/rules/SA00008/CompensateInRepeatUntil.bpel", "8"},
                {"Testcases/rules/SA00008/CompensateInScope.bpel", "8"},
                {"Testcases/rules/SA00008/CompensateInWhile.bpel", "8"},

                {"Testcases/rules/SA00010/UndefinedType-Catch-FaultElement.bpel", "10"},
                {"Testcases/rules/SA00010/UndefinedType-Catch-FaultMessageType.bpel", "10"},
                {"Testcases/rules/SA00010/UndefinedType-CorrelationSet.bpel", "10"},
                {"Testcases/rules/SA00010/UndefinedType-From.bpel", "10, 21"},
                {"Testcases/rules/SA00010/UndefinedType-Invoke.bpel", "10"},
                {"Testcases/rules/SA00010/UndefinedType-OnEvent.bpel", "10, 84"},
                {"Testcases/rules/SA00010/UndefinedType-OnMessage.bpel", "10"},
                {"Testcases/rules/SA00010/UndefinedType-PartnerLink.bpel", "10"},
                {"Testcases/rules/SA00010/UndefinedType-Receive.bpel", "10"},
                {"Testcases/rules/SA00010/UndefinedType-Reply.bpel", "10"},
                {"Testcases/rules/SA00010/UndefinedType-To.bpel", "10, 21"},
                {"Testcases/rules/SA00010/UndefinedType-Variable-Element.bpel", "10"},
                {"Testcases/rules/SA00010/UndefinedType-Variable-MessageType.bpel", "10"},
                {"Testcases/rules/SA00010/UndefinedType-Variable-Type.bpel", "10"},
                {"Testcases/rules/SA00010/InvokeUndefinedPartnerLink.bpel", "10"},
                {"Testcases/rules/SA00010/OnEventUndefinedElement.bpel", "10, 87"},
                {"Testcases/rules/SA00010/OnEventUndefinedMessageType.bpel", "10, 87"},
                {"Testcases/rules/SA00010/OnEventUndefinedPartnerLink.bpel", "10, 84"},
                {"Testcases/rules/SA00010/OnMessageUndefinedPartnerLink.bpel", "10"},
                {"Testcases/rules/SA00010/ReceiveUndefinedPartnerLink.bpel", "10"},
                {"Testcases/rules/SA00010/ReplyUndefinedPartnerLink.bpel", "10"},

                {"Testcases/rules/SA00011/Import-WrongNameSpace.bpel", "11"},

                {"Testcases/rules/SA00012/Import-NoNameSpace.bpel", "12"},

                {"Testcases/rules/SA00013/Import-WrongImportType.bpel", "13"},
                {"Testcases/rules/SA00013/WrongXsdImportType.bpel", "13"},

                {"Testcases/rules/SA00014/ImportRedefine.bpel", "14"},
                {"Testcases/rules/SA00014/ImportWsdlAndWsdlCopy.bpel", "14"},
                {"Testcases/rules/SA00014/ImportXsdAndDefineInside.bpel", "14"},
                {"Testcases/rules/SA00014/ImportXsdAndWsdlXsdCopy.bpel", "14"},
                {"Testcases/rules/SA00014/ImportXsdAndXsdCopy.bpel", "14"},

                {"Testcases/rules/SA00015/NoActivityWithCreateInstanceSetToYes.bpel", "15"},
                {"Testcases/rules/SA00015/OnlyActivityWithCreateInstanceSetToNo.bpel", "15"},
                {"Testcases/rules/SA00015/PickCreateInstanceMissing.bpel", "15"},
                {"Testcases/rules/SA00015/PickCreateInstanceNo.bpel", "15"},

                {"Testcases/rules/SA00016/PartnerLinkWithoutMyRoleAndPartnerRole.bpel", "16, 10"},

                {"Testcases/rules/SA00017/InitializePartnerRoleUsedOnPartnerLinkWithoutPartnerRole.bpel", "17"},

                {"Testcases/rules/SA00018/TwoPartnerLinksWithSameName.bpel", "18"},
                {"Testcases/rules/SA00018/ScopeSamePartnerLinkTwice.bpel", "18"},

                {"Testcases/rules/SA00019/PropertyWithoutTypeOrElement.bpel", "19"},
                {"Testcases/rules/SA00019/PropertyWithTypeAndElement.bpel", "19"},

                {"Testcases/rules/SA00020/PropertyAlias-AllOptionalAttributes.bpel", "20"},
                {"Testcases/rules/SA00020/PropertyAlias-MessageTypeAttribute.bpel", "20"},
                {"Testcases/rules/SA00020/PropertyAlias-MessageTypeElementAttributes.bpel", "20"},
                {"Testcases/rules/SA00020/PropertyAlias-MessageTypePartElementAttributes.bpel", "20"},
                {"Testcases/rules/SA00020/PropertyAlias-MessageTypePartTypeAttributes.bpel", "20"},
                {"Testcases/rules/SA00020/PropertyAlias-MessageTypeTypeAttributes.bpel", "20"},
                {"Testcases/rules/SA00020/PropertyAlias-MessageTypeTypeElementAttributes.bpel", "20"},
                {"Testcases/rules/SA00020/PropertyAlias-NoOptionalAttributes.bpel", "20"},
                {"Testcases/rules/SA00020/PropertyAlias-PartAttribute.bpel", "20"},
                {"Testcases/rules/SA00020/PropertyAlias-PartElementAttributes.bpel", "20"},
                {"Testcases/rules/SA00020/PropertyAlias-PartTypeAttributes.bpel", "20"},
                {"Testcases/rules/SA00020/PropertyAlias-PartTypeElementAttributes.bpel", "20"},
                {"Testcases/rules/SA00020/PropertyAlias-TypeElementAttributes.bpel", "20"},

                {"Testcases/rules/SA00021/From-Property-AlienAlias.bpel", "21"},
                {"Testcases/rules/SA00021/OnEvent-Variable-AlienAlias.bpel", "21"},
                {"Testcases/rules/SA00021/To-Property-AlienAlias.bpel", "21"},
                {"Testcases/rules/SA00021/InvokeToCorrelationAlienAlias.bpel", "21"},
                {"Testcases/rules/SA00021/OnEventCorrelationAlienAlias.bpel", "21"},
                {"Testcases/rules/SA00021/OnMessageCorrelationAlienAlias.bpel", "21"},
                {"Testcases/rules/SA00021/ReceiveCorrelationAlienAlias.bpel", "21"},
                {"Testcases/rules/SA00021/ReplyCorrelationAlienAlias.bpel", "21"},

                {"Testcases/rules/SA00022/Duplicate-propertyAliasElement.bpel", "22"},
                {"Testcases/rules/SA00022/Duplicate-propertyAliasMessageType.bpel", "22"},
                {"Testcases/rules/SA00022/Duplicate-propertyAliasType.bpel", "22"},
                {"Testcases/rules/SA00022/DoubleImportedPropertyAlias.bpel", "22"},

                {"Testcases/rules/SA00023/Process-Duplicated-Variables.bpel", "23"},
                {"Testcases/rules/SA00023/Scope-Duplicated-Variables.bpel", "23"},
                {"Testcases/rules/SA00023/Scope-Scope-Duplicated-Variables_IGNORE_ME.bpel", "23"},

                {"Testcases/rules/SA00025/Variable-havingMessageTypeAndElement.bpel", "25"},
                {"Testcases/rules/SA00025/Variable-havingTypeAndElement.bpel", "25"},
                {"Testcases/rules/SA00025/Variable-havingTypeAndMessageType.bpel", "25"},
                {"Testcases/rules/SA00025/Variable-havingTypeAndMessageTypeAndElement.bpel", "25"},
                {"Testcases/rules/SA00025/Variable-missingMessageTypeAndTypeAndElement.bpel", "25"},

                {"Testcases/rules/SA00032/ToMessageTypeVariableSuperfluousAttribute.bpel", "32"},
                {"Testcases/rules/SA00032/ToVariableSuperfliciousChild.bpel", "32"},
                {"Testcases/rules/SA00032/FromMessageTypeVariableSuperfliciousAttribute.bpel", "32"},
                {"Testcases/rules/SA00032/FromVariableSuperfliciousChild.bpel", "32"},
                {"Testcases/rules/SA00032/ToPartnerLinkSuperfliciousChild.bpel", "32"},
                {"Testcases/rules/SA00032/ToPartnerLinkSuperfliciousAttribute.bpel", "32"},
                {"Testcases/rules/SA00032/FromVariableQuerySuperfliciousAttribute.bpel", "32"},
                {"Testcases/rules/SA00032/ToVariableQuerySuperfliciousAttribute.bpel", "32"},
                {"Testcases/rules/SA00032/FromPartnerLinkSuperfliciousAttribute.bpel", "32"},
                {"Testcases/rules/SA00032/FromPartnerLinkSuperfliciousChild.bpel", "32"},
                {"Testcases/rules/SA00032/FromPartnerLinkMissingEndpointReferenceAttribute.bpel", "32"},
                {"Testcases/rules/SA00032/FromVariablePropertySuperfliciousAttribute.bpel", "32"},
                {"Testcases/rules/SA00032/FromVariablePropertySuperfliciousChild.bpel", "32"},
                {"Testcases/rules/SA00032/FromExpressionLanguageSuperfliciousAttributes.bpel", "32"},
                {"Testcases/rules/SA00032/ToExpressionLanguageSuperfliciousAttributes.bpel", "32"},
                {"Testcases/rules/SA00032/FromExpressionLanguageSuperfliciousChild.bpel", "32"},
                {"Testcases/rules/SA00032/ToExpressionLanguageSuperfliciousChild.bpel", "32"},
                {"Testcases/rules/SA00032/FromLiteralSuperfliciousAttribute.bpel", "32"},
                {"Testcases/rules/SA00032/FromLiteralSuperfliciousChild.bpel", "32"},
                {"Testcases/rules/SA00032/ToVariablePropertySuperfliciousAttribute.bpel", "32"},
                {"Testcases/rules/SA00032/ToVariablePropertySuperfliciousChild.bpel", "32"},
                {"Testcases/rules/SA00032/FromVariableQueryAdditionalAttribute.bpel", "32"},
                {"Testcases/rules/SA00032/FromVariableQueryAdditionalChild.bpel", "32"},
                {"Testcases/rules/SA00032/ToVariableQueryAdditionalAttribute.bpel", "32"},
                {"Testcases/rules/SA00032/ToVariableQueryAdditionalChild.bpel", "32"},

                {"Testcases/rules/SA00034/FromElementVariablePartAttribute.bpel", "34"},
                {"Testcases/rules/SA00034/FromOnEventElementVariablePartAttribute.bpel", "34"},
                {"Testcases/rules/SA00034/FromTypeVariablePartAttribute.bpel", "34"},
                {"Testcases/rules/SA00034/ToElementVariablePartAttribute.bpel", "34"},
                {"Testcases/rules/SA00034/ToOnEventElementVariablePartAttribute.bpel", "34"},
                {"Testcases/rules/SA00034/ToTypeVariablePartAttribute.bpel", "34"},

                {"Testcases/rules/SA00035/FromLinkTypeMyRolePartnerLinkWithoutMyRole.bpel", "35"},

                {"Testcases/rules/SA00036/FromPartnerRoleWithoutPartnerRolePartnerLink.bpel", "36"},

                {"Testcases/rules/SA00037/ToLinkTypeWithoutPartnerRolePartnerLink.bpel", "37"},

                {"Testcases/rules/SA00044/Process-CorrelationSet-Ambiguous.bpel", "44"},
                {"Testcases/rules/SA00044/Scope-CorrelationSets-Ambiguous.bpel", "44"},

                {"Testcases/rules/SA00045/Property-TypeComplexType.bpel", "45, 21"}, // SA00021 is violated because complexType cannot be aliased by int
                {"Testcases/rules/SA00045/Property-TypeMissing.bpel", "45, 19, 21"}, // SA00021 is violated because no type cannot be aliased by int

                {"Testcases/rules/SA00046/Invoke-OneWay-Correlation-Pattern.bpel", "46"},
                {"Testcases/rules/SA00046/Invoke-RequestResponse-Correlation-PatternMissing.bpel", "46"},

                {"Testcases/rules/SA00047/EmptyMessage-Invoke-FromParts.bpel", "47, 53"},
                {"Testcases/rules/SA00047/EmptyMessage-Invoke-ToParts-FromParts_IGNORE_ME.bpel", "47, 54, 53"},
                {"Testcases/rules/SA00047/EmptyMessage-Invoke-ToParts.bpel", "47, 54"},
                {"Testcases/rules/SA00047/EmptyMessage-OnEvent-FromParts.bpel", "47, 53, 88, 21"}, // SA00021 is violated because empty message cannot correlate
                {"Testcases/rules/SA00047/EmptyMessage-OnMessage-FromParts.bpel", "47, 53"},
                {"Testcases/rules/SA00047/EmptyMessage-Receive-FromParts.bpel", "47, 53"},
                {"Testcases/rules/SA00047/EmptyMessage-Reply-ToParts.bpel", "47, 54"},
                {"Testcases/rules/SA00047/Invoke-OneWay-NoInputVariable-NoToParts.bpel", "47"},
                {"Testcases/rules/SA00047/Invoke-RequestResponse-NoInputOutputVariables-NoToFromParts_IGNORE_ME.bpel", "47"},
                {"Testcases/rules/SA00047/Invoke-RequestResponse-NoInputVariable-NoToParts_IGNORE_ME.bpel", "47"},
                {"Testcases/rules/SA00047/Invoke-RequestResponse-NoOutputVariable-NoFromParts.bpel", "47"},
                {"Testcases/rules/SA00047/NoVariable-NoFromPart-OnEvent.bpel", "47"},
                {"Testcases/rules/SA00047/NoVariable-NoFromPart-OnMessage.bpel", "47"},
                {"Testcases/rules/SA00047/NoVariable-NoFromPart-Receive.bpel", "47"},
                {"Testcases/rules/SA00047/NoVariable-NoToPart-NoFromPart-ReceiveReply_IGNORE_ME.bpel", "47"},
                {"Testcases/rules/SA00047/NoVariable-NoToPart-Reply.bpel", "47"},

                {"Testcases/rules/SA00048/InputOutputVariable-Message-NotFound.bpel", "48"},
                {"Testcases/rules/SA00048/InputVariable-MessageType-Message-NotFound.bpel", "48"},
                {"Testcases/rules/SA00048/InputVariable-Type-MessageManyParts.bpel", "48"},
                {"Testcases/rules/SA00048/InputVariable-Type-MessageOnePart-NotFound.bpel", "48"},
                {"Testcases/rules/SA00048/OutputVariable-MessageType-Message-NotFound.bpel", "48"},
                {"Testcases/rules/SA00048/OutputVariable-Type-MessageManyParts.bpel", "48"},
                {"Testcases/rules/SA00048/OutputVariable-Type-MessageOnePart-NotFound.bpel", "48"},

                {"Testcases/rules/SA00050/Invoke-MissingToPart.bpel", "50"},
                {"Testcases/rules/SA00050/Receive-MissingToPart.bpel", "50"},

                {"Testcases/rules/SA00051/Invoke-ToPartsAndInputVariable.bpel", "51"},

                {"Testcases/rules/SA00052/Invoke-FromPartsAndOutputVariable.bpel", "52"},

                {"Testcases/rules/SA00053/Invoke-FromPartDifferingFromMessageDefinition.bpel", "53"},
                {"Testcases/rules/SA00053/OnEvent-FromPartDifferingFromMessageDefinition.bpel", "53"},
                {"Testcases/rules/SA00053/OnMessage-FromPartDifferingFromMessageDefinition.bpel", "53"},
                {"Testcases/rules/SA00053/Receive-FromPartDifferingFromMessageDefinition.bpel", "53"},

                {"Testcases/rules/SA00054/Invoke-ToPartDifferingFromMessageDefinition.bpel", "54"},
                {"Testcases/rules/SA00054/Reply-ToPartDifferingFromMessageDefinition.bpel", "54"},

                {"Testcases/rules/SA00055/Receive-WithFromPartElementAndVariableAttribute.bpel", "55"},

                {"Testcases/rules/SA00056/StartPickInCatch.bpel", "56"},
                {"Testcases/rules/SA00056/StartPickInCatchAll.bpel", "56"},
                {"Testcases/rules/SA00056/StartPickInElse.bpel", "56"},
                {"Testcases/rules/SA00056/StartPickInElseIf.bpel", "56"},
                {"Testcases/rules/SA00056/StartPickInForEach.bpel", "56"},
                {"Testcases/rules/SA00056/StartPickInIf.bpel", "56"},
                {"Testcases/rules/SA00056/StartPickInNonStartPick.bpel", "56, 57"},
                {"Testcases/rules/SA00056/StartPickInOnAlarm.bpel", "56, 57"},
                {"Testcases/rules/SA00056/StartPickInOnEvent.bpel", "56, 57"},
                {"Testcases/rules/SA00056/StartPickInRepeatUntil.bpel", "56"},
                {"Testcases/rules/SA00056/StartPickInTerminationHandlers.bpel", "56"},
                {"Testcases/rules/SA00056/StartPickInWhile.bpel", "56"},
                {"Testcases/rules/SA00056/StartPickParalellNonStartPick.bpel", "56"},
                {"Testcases/rules/SA00056/StartPickParalellNonStartReceive.bpel", "56"},
                {"Testcases/rules/SA00056/StartPickPreviousNonStartPick.bpel", "56"},
                {"Testcases/rules/SA00056/StartPickPreviousNonStartReceive.bpel", "56"},
                {"Testcases/rules/SA00056/StartReceiveInCatch.bpel", "56"},
                {"Testcases/rules/SA00056/StartReceiveInCatchAll.bpel", "56"},
                {"Testcases/rules/SA00056/StartReceiveInElse.bpel", "56"},
                {"Testcases/rules/SA00056/StartReceiveInElseIf.bpel", "56"},
                {"Testcases/rules/SA00056/StartReceiveInForEach.bpel", "56"},
                {"Testcases/rules/SA00056/StartReceiveInIf.bpel", "56"},
                {"Testcases/rules/SA00056/StartReceiveInNonStartPick.bpel", "56, 57"},
                {"Testcases/rules/SA00056/StartReceiveInOnAlarm.bpel", "56, 57"},
                {"Testcases/rules/SA00056/StartReceiveInOnEvent.bpel", "56, 57"},
                {"Testcases/rules/SA00056/StartReceiveInRepeatUntil.bpel", "56"},
                {"Testcases/rules/SA00056/StartReceiveInTerminationHandlers.bpel", "56"},
                {"Testcases/rules/SA00056/StartReceiveInWhile.bpel", "56"},
                {"Testcases/rules/SA00056/StartReceiveParalellNonStartPick.bpel", "56"},
                {"Testcases/rules/SA00056/StartReceiveParalellNonStartReceive.bpel", "56"},
                {"Testcases/rules/SA00056/StartReceivePreviousNonStartPick.bpel", "56"},
                {"Testcases/rules/SA00056/StartReceivePreviousNonStartReceive.bpel", "56"},
                {"Testcases/rules/SA00056/FlowLateStartReceive.bpel", "56"},

                {"Testcases/rules/SA00057/OnMessageCorrelationYesAndJoin.bpel", "57"},
                {"Testcases/rules/SA00057/OnMessageReceiveCorrelationYesAndJoin.bpel", "57"},
                {"Testcases/rules/SA00057/ReceiveCorrelationYesAndJoin.bpel", "57"},
                {"Testcases/rules/SA00057/OnMessageSingleCorrelation.bpel", "57"},
                {"Testcases/rules/SA00057/OnMessageReceiveSingleCorrelation.bpel", "57"},
                {"Testcases/rules/SA00057/ReceiveSingleCorrelation.bpel", "57"},

                {"Testcases/rules/SA00058/ReceiveDeviantMessageType.bpel", "58"},
                {"Testcases/rules/SA00058/ReceiveDeviantType.bpel", "58"},
                {"Testcases/rules/SA00058/ReceiveReplyDeviantTypes.bpel", "58"},
                {"Testcases/rules/SA00058/ReceiveTwoPartsPartType.bpel", "58"},
                {"Testcases/rules/SA00058/ReplyDeviantMessageType.bpel", "58"},
                {"Testcases/rules/SA00058/ReplyDeviantType.bpel", "58"},
                {"Testcases/rules/SA00058/ReplyTwoPartsPartType.bpel", "58"},
                {"Testcases/rules/SA00058/ReceiveTwoPartsDifferentElement.bpel", "58"},
                {"Testcases/rules/SA00058/ReplyTwoPartsDifferentElement.bpel", "58"},
                {"Testcases/rules/SA00058/ReceiveTwoPartsType.bpel", "58"},
                {"Testcases/rules/SA00058/ReplyTwoPartsType.bpel", "58"},
                {"Testcases/rules/SA00058/ReceiveType.bpel", "58"},
                {"Testcases/rules/SA00058/ReplyType.bpel", "58"},
//                {"Testcases/rules/SA00058/.bpel", "58"},
//                {"Testcases/rules/SA00058/.bpel", "58"},
//                {"Testcases/rules/SA00058/.bpel", "58"},
//                {"Testcases/rules/SA00058/.bpel", "58"},
//                {"Testcases/rules/SA00058/.bpel", "58"},
//                {"Testcases/rules/SA00058/.bpel", "58"},

                {"Testcases/rules/SA00059/Reply-WithToPartElementAndVariableAttribute.bpel", "59"},

                {"Testcases/rules/SA00060/OnMessageFifoFirstMexMissing.bpel", "60"},
                {"Testcases/rules/SA00060/OnMessageFifoSecondMexMissing.bpel", "60"},
                {"Testcases/rules/SA00060/OnMessageFiloFirstMexMissing.bpel", "60"},
                {"Testcases/rules/SA00060/OnMessageFiloSecondMexMissing.bpel", "60"},
                {"Testcases/rules/SA00060/ReceiveFifoFirstMexMissing.bpel", "60"},
                {"Testcases/rules/SA00060/ReceiveFifoSecondMexMissing.bpel", "60"},
                {"Testcases/rules/SA00060/ReceiveFiloFirstMexMissing.bpel", "60"},
                {"Testcases/rules/SA00060/ReceiveFiloSecondMexMissing.bpel", "60"},
                {"Testcases/rules/SA00060/OnEventFiloFirstMexMissing.bpel", "60"},
                {"Testcases/rules/SA00060/OnEventFiloSecondMexMissing.bpel", "60"},

                {"Testcases/rules/SA00061/OnEventMessageExchangeNotInScope.bpel", "61"},
                {"Testcases/rules/SA00061/OnEventNoMessageExchangeInScope.bpel", "61, 89"},
                {"Testcases/rules/SA00061/OnEventReplyMessageExchangeNotInScope.bpel", "61"},
                {"Testcases/rules/SA00061/OnEventMessageExchangeNotInProcess.bpel", "61"},
                {"Testcases/rules/SA00061/OnEventNoMessageExchangeInProcess.bpel", "61, 89"},
                {"Testcases/rules/SA00061/OnEventReplyMessageExchangeNotInProcess.bpel", "61"},
                {"Testcases/rules/SA00061/OnMessageMessageExchangeNotInProcess.bpel", "61"},
                {"Testcases/rules/SA00061/OnMessageMessageExchangeOutOfScope.bpel", "61"},
                {"Testcases/rules/SA00061/OnMessageNoMessageExchangeInProcess.bpel", "61"},
                {"Testcases/rules/SA00061/OnMessageReplyMessageExchangeNotInProcess.bpel", "61"},
                {"Testcases/rules/SA00061/OnMessageMessageExchangeNotInScope.bpel", "61"},
                {"Testcases/rules/SA00061/OnMessageNoMessageExchangeInScope.bpel", "61"},
                {"Testcases/rules/SA00061/OnMessageReplyMessageExchangeNotInScope.bpel", "61"},
                {"Testcases/rules/SA00061/ReceiveMessageExchangeNotInProcess.bpel", "61"},
                {"Testcases/rules/SA00061/ReceiveMessageExchangeNotInScope.bpel", "61"},
                {"Testcases/rules/SA00061/ReceiveMessageExchangeOutOfScope.bpel", "61"},
                {"Testcases/rules/SA00061/ReceiveNoMessageExchangeInProcess.bpel", "61"},
                {"Testcases/rules/SA00061/ReceiveNoMessageExchangeInScope.bpel", "61"},
                {"Testcases/rules/SA00061/ReceiveReplyMessageExchangeNotInProcess.bpel", "61"},
                {"Testcases/rules/SA00061/ReceiveReplyMessageExchangeNotInScope.bpel", "61"},

                {"Testcases/rules/SA00062/Pick-CreateInstanceWithOnAlarm.bpel", "62"},

                {"Testcases/rules/SA00063/OnMessage-With-FromPartAndAttributeVariable.bpel", "63"},

                {"Testcases/rules/SA00064/LinkNameDuplicate.bpel", "64"},

                {"Testcases/rules/SA00065/NoLink.bpel", "65"},
                {"Testcases/rules/SA00065/SourceLinkIsMissing.bpel", "65, 66"},
                {"Testcases/rules/SA00065/SourceLinkOutOfFlow.bpel", "65, 66"},
                {"Testcases/rules/SA00065/TargetLinkIsMissing.bpel", "65, 66"},
                {"Testcases/rules/SA00065/TargetLinkOutOfFlow.bpel", "65, 66"},

                {"Testcases/rules/SA00066/LinkTwoSources.bpel", "66"},
                {"Testcases/rules/SA00066/LinkTwoTargets.bpel", "66"},
                {"Testcases/rules/SA00066/LinkNoSource.bpel", "66"},
                {"Testcases/rules/SA00066/LinkNoTarget.bpel", "66"},
                {"Testcases/rules/SA00066/LinkTwoSourcesNoTarget.bpel", "66"},
                {"Testcases/rules/SA00066/LinkTwoTargetsNoSource.bpel", "66"},

                {"Testcases/rules/SA00067/DoubleLink.bpel", "67"},

                {"Testcases/rules/SA00068/LinkSourceDuplicate.bpel", "68"},

                {"Testcases/rules/SA00069/LinkTargetDuplicate.bpel", "69"},

                {"Testcases/rules/SA00070/SourceOutOfWhile.bpel", "70"},
                {"Testcases/rules/SA00070/SourceOutOfRepeatUntil.bpel", "70"},
                {"Testcases/rules/SA00070/SourceOutOfForEach.bpel", "70"},
                {"Testcases/rules/SA00070/SourceOutOfEventHandlers.bpel", "70"},
                {"Testcases/rules/SA00070/SourceOutOfCompensationHandler.bpel", "70, 56"}, // TODO this test can be modified by betsy test modification placing the start activity before the flow
                {"Testcases/rules/SA00070/TargetOutOfWhile.bpel", "70"},
                {"Testcases/rules/SA00070/TargetOutOfRepeatUntil.bpel", "70"},
                {"Testcases/rules/SA00070/TargetOutOfForEach.bpel", "70"},
                {"Testcases/rules/SA00070/TargetOutOfEventHandlers.bpel", "70"},
                {"Testcases/rules/SA00070/TargetOutOfCompensationHandler.bpel", "70"},
                {"Testcases/rules/SA00070/LinkOutOfWhile.bpel", "70"},
                {"Testcases/rules/SA00070/LinkOutOfRepeatUntil.bpel", "70"},
                {"Testcases/rules/SA00070/LinkOutOfForEach.bpel", "70"},
                {"Testcases/rules/SA00070/LinkOutOfEventHandlers.bpel", "70"},
                {"Testcases/rules/SA00070/LinkOutOfCompensationHandler.bpel", "70"},

                {"Testcases/rules/SA00071/CatchIncommingLink.bpel", "71, 56"}, // TODO this test can be modified by betsy test modification placing the start activity before the flow
                {"Testcases/rules/SA00071/CatchAllIncommingLink.bpel", "71, 56"}, // TODO this test can be modified by betsy test modification placing the start activity before the flow
                {"Testcases/rules/SA00071/TerminationHandlerIncommingLink.bpel", "71"},

                {"Testcases/rules/SA00072/FlowSelfLinked.bpel", "72"},
                {"Testcases/rules/SA00072/FlowCyclic.bpel", "72"},
                {"Testcases/rules/SA00072/FlowCyclicSubGraph_IGNORE_ME.bpel", "72"},

                {"Testcases/rules/SA00076/ForEach-DuplicateCounterVariable.bpel", "76"},

                {"Testcases/rules/SA00077/NoCompensateTarget.bpel", "77"},
                {"Testcases/rules/SA00077/CompensateTargetScopeNestedInScope.bpel", "77"},
                {"Testcases/rules/SA00077/CompensateTargetInvokeNestedInScope.bpel", "77"},
                {"Testcases/rules/SA00077/CompensateTargetScopeNestedInCatch.bpel", "77, 79"},
                {"Testcases/rules/SA00077/CompensateTargetInvokeNestedInCatch.bpel", "77"},
                {"Testcases/rules/SA00077/CompensateTargetScopeNestedInCatchAll.bpel", "77, 79"},
                {"Testcases/rules/SA00077/CompensateTargetInvokeNestedInCatchAll.bpel", "77"},
                {"Testcases/rules/SA00077/CompensateTargetScopeNestedInCompensationHandler.bpel", "77, 79"},
                {"Testcases/rules/SA00077/CompensateTargetInvokeNestedInCompensationHandler.bpel", "77"},
                {"Testcases/rules/SA00077/CompensateTargetScopeNestedInTerminationHandler.bpel", "77, 79"},
                {"Testcases/rules/SA00077/CompensateTargetInvokeNestedInTerminationHandler.bpel", "77"},
                {"Testcases/rules/SA00077/CompensateTargetScopeOutOfScope.bpel", "77"},
                {"Testcases/rules/SA00077/CompensateTargetInvokeOutOfScope.bpel", "77"},

                {"Testcases/rules/SA00078/ScopeMissingFCHandler.bpel", "78"},
                {"Testcases/rules/SA00078/InvokeMissingFCHandler.bpel", "78"},

                {"Testcases/rules/SA00079/CompensationHandlerInCatchRootScope.bpel", "79"},
                {"Testcases/rules/SA00079/CompensationHandlerInCatchAllRootScope.bpel", "79"},
                {"Testcases/rules/SA00079/HandlersCompensationInTerminationRootScope.bpel", "79"},
                {"Testcases/rules/SA00079/HandlersCompensationInCompensationRootScope.bpel", "79"},

                {"Testcases/rules/SA00080/EmptyFaultHandlersInProcess.bpel", "80"},
                {"Testcases/rules/SA00080/EmptyFaultHandlersInScope.bpel", "80"},

                {"Testcases/rules/SA00081/CatchVariableTypeElement.bpel", "81"},
                {"Testcases/rules/SA00081/CatchVariable.bpel", "81"},
                {"Testcases/rules/SA00081/CatchType.bpel", "81"},
                {"Testcases/rules/SA00081/CatchElement.bpel", "81"},
                {"Testcases/rules/SA00081/CatchTypeElement.bpel", "81"},

                {"Testcases/rules/SA00082/CyclicLinkedPeerScopes.bpel", "82"},

                {"Testcases/rules/SA00083/EmptyEventHandlersInProcess.bpel", "83"},
                {"Testcases/rules/SA00083/EmptyEventHandlersInScope.bpel", "83"},

                {"Testcases/rules/SA00084/OnEventScopeDifferingPartnerLinkOperation_IGNORE_ME.bpel", "84, 10"},
                {"Testcases/rules/SA00084/OnEventScopeDifferingPartnerLinkRole.bpel", "84"},
                {"Testcases/rules/SA00084/OnEventScopeNoPartnerLink_IGNORE_ME.bpel", "84, 10"},

                {"Testcases/rules/SA00085/OnEventFormPartsVariableElement.bpel", "85"},
                {"Testcases/rules/SA00085/OnEventFormPartsVariableMessageType.bpel", "85"},
                {"Testcases/rules/SA00085/OnEventFormPartsElement.bpel", "85"},
                {"Testcases/rules/SA00085/OnEventFormPartsMessageType.bpel", "85"},
                {"Testcases/rules/SA00085/OnEventFormPartsElementMessageType.bpel", "85"},

                {"Testcases/rules/SA00086/OnEventExplicitVaribaleDoublicate.bpel", "86"},
                {"Testcases/rules/SA00086/OnEventExplicitFromPartToVaribaleDoublicate.bpel", "86"},

                {"Testcases/rules/SA00087/OnEventElementTwoParts.bpel", "87"},
                {"Testcases/rules/SA00087/OnEventUnresolvedElement.bpel", "87, 10"},
                {"Testcases/rules/SA00087/OnEventUnresolvedMessageType_IGNORE_ME.bpel", "87, 10"},
                {"Testcases/rules/SA00087/OnEventDifferentElementTwoPart.bpel", "87"},
                {"Testcases/rules/SA00087/OnEventElementEmpty.bpel", "87"},

                {"Testcases/rules/SA00088/OnEventCorrelationWrongType.bpel", "88"},
                {"Testcases/rules/SA00088/OnEventCorrelationNoSet_IGNORE_ME.bpel", "88"},
                {"Testcases/rules/SA00088/OnEventCorrelationSetUnreachable_IGNORE_ME.bpel", "88"},

                {"Testcases/rules/SA00089/OnEventNoMessageExchange.bpel", "89, 61"},

                {"Testcases/rules/SA00090/OnEventVariable.bpel", "90"},
                {"Testcases/rules/SA00090/OnEventVariableElementMessageType.bpel", "90"},

                {"Testcases/rules/SA00091/IsolatedScopeInIsolatedSope.bpel", "91"},

                {"Testcases/rules/SA00092/ScopeNameDuplicate.bpel", "92"},
                {"Testcases/rules/SA00092/ScopeNameDuplicateInScope.bpel", "92"},

                {"Testcases/rules/SA00093/SameCatchFaultElement.bpel", "93"},
                {"Testcases/rules/SA00093/SameCatchFaultElementFaultName.bpel", "93"},
                {"Testcases/rules/SA00093/SameCatchFaultMessageType.bpel", "93"},
                {"Testcases/rules/SA00093/SameCatchFaultMessageTypeFaultName.bpel", "93"},
                {"Testcases/rules/SA00093/SameCatchFaultName.bpel", "93"},

                {"Testcases/rules/SA00095/OnEventVariableOutboundUseAssign.bpel", "95, 34"},
                {"Testcases/rules/SA00095/OnEventVariableOutboundUseReceive_IGNORE_ME.bpel", "95"},

        };
        return Arrays.asList(data);
    }
}
