<?xml version="1.0" encoding="UTF-8"?>
<definitions 
    name="CalculatorService"
    targetNamespace="http://j2ee.netbeans.org/wsdl/CalculatorService/CalculatorService"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:tns="http://j2ee.netbeans.org/wsdl/CalculatorService/CalculatorService"
    xmlns:ns="http://xml.netbeans.org/schema/CalculatorSchema"
    xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">

    <plnk:partnerLinkType name="CalculatorService">
        <plnk:role name="CalculatorServicePortTypeRole" portType="tns:CalculatorServicePortType"/>
    </plnk:partnerLinkType>

    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/CalculatorService/CalculatorService">
            <xsd:import namespace="http://xml.netbeans.org/schema/CalculatorSchema" schemaLocation="CalculatorSchema.xsd"/>
        </xsd:schema>
    </types>
    <message name="CalculatorServiceOperationRequest">
        <part name="inputMessage" element="ns:calculationInput"/>
    </message>
    <message name="CalculatorServiceOperationResponse">
        <part name="responseMessage" element="ns:calculationResult"/>
    </message>
    <message name="CalculatorServiceOperationFault">
   <!--
   <part name="faultMessage" element="ns:faultResult"/>
-->
        <part name="faultMessage" type="xs:string"/>
    </message>


    <portType name="CalculatorServicePortType">
        <operation name="CalculatorServiceOperation">
            <input name="input1" message="tns:CalculatorServiceOperationRequest"/>
            <output name="output1" message="tns:CalculatorServiceOperationResponse"/>
            <fault name="fault1" message="tns:CalculatorServiceOperationFault"/>
        </operation>
    </portType>
    <binding name="CalculatorServiceBinding" type="tns:CalculatorServicePortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="CalculatorServiceOperation">
            <soap:operation/>
            <input name="input1">
                <soap:body use="literal"/>
            </input>
            <output name="output1">
                <soap:body use="literal"/>
            </output>
            <fault name="fault1">
                <soap:fault name="fault1" use="literal"/>
            </fault>
        </operation>
    </binding>
    <service name="CalculatorServiceService">
        <port name="CalculatorServicePort" binding="tns:CalculatorServiceBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/CalculatorServiceService/CalculatorServicePort"/>
        </port>
    </service>

</definitions>

